### ISSUE TITLE
How to build spk from files in this repository?

### ISSUE THREAD

**Issue by fbartels** [TosoBoso/Kopano4s#1]
Hi @TosoBoso ,

thanks for uploading your code to github! Looking through the code I am missing instructions how to generate a spk file from this repo (to locally try out changes. 

I have recently refactored the buildscript for synocr (https://geimist.eu:30443/geimist/synOCR) but at first glance this repo has a different structure and also some differing subfolders. 

Maybe adding something like https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447 to upload the resulting spk to a "release" (basically a git tag) to Github would be interesting as well.

In https://github.com/zokradonh/kopano-docker/ there is also a Makefile to build and upload the Docker containers. Maybe this could be interesting in this repo as well?

Edit: instead of the script above uploading (and building a release) could also be done through Travis. Travis is free for public github projects: https://docs.travis-ci.com/user/deployment/releases/

**Comment by TosoBoso** [comment]
I added a section How to Clone, Test & Collaborate in the readme which is non magic manual task.

As outlined in https://wiki.z-hub.io/display/K4S the source code is wrapped in a SPK file which is a simple tar that can be modified e.g. using 7Zip. The modified files are to be replaced in the SPK and the signature to be removed.  There is no tool-chain logic that automatically builds this SPK (though Synnocommunity are using such techniques which can make sense when cross compiling).
For the advanced options with building spk, tagging, buidling docker etc. I will have a look at it. Currently the SPK is doing the Docker build incl. setting the file names to download (incl. SNR for supported builds keeping credentials in a intermediate container which I would not want to automate by makefile.

**Comment by fbartels** [comment]
Should I add a script to build and a travis file?

**Comment by fbartels** [comment]
Is that a "no"?

**Comment by TosoBoso** [comment]
I need to digest adn understand build and travis file so it is a don't know yet but not a no

**Comment by fbartels** [comment]
Should I open a pr with these two so you can digest and understand based on these?

I would not have expected that you have a travis file for it yet, but maybe you had small scriptlet to create the spk locally. Like I said in the opening question I have recently refactored a different script so I could modify and add this script here as well.

**Comment by TosoBoso** [comment]
No travis files no scriptlets to create the spk locally just old school replacing files. You can modify and add script(s).
