### ISSUE TITLE
Initial installation fails

### ISSUE THREAD

**Issue by cnoork** [TosoBoso/Kopano4s#4]
Hi, I like to migrate from Zarafa to Kopano but my first tests to install Kopano are still failing. I did the following steps:

- git clone https://github.com/TosoBoso/Kopano4s.git
- ./build_spk.sh
- copy the spk to my laptop
- in Package Center did the Manual Install from the spk
- keep setting default, except domain en smtp

After starting Kopano4s I get the msgs: "Failed to run the package service"

What could the cause and where can I find a logging to see a msgs? Any help would be great.

I have DS918+ with 16GB Ram and some other docker containers running.

**Comment by TosoBoso** [comment]
Hi cnoork,
4 items: 1) how to get / build spk, 2) support, wiki, forum  3) logging, 4) migration
1) The fastest and simplest way is to use the signed SPK package from the Community Package Hub : https://www.cphub.net/?p=k4s . Though the git-clone and build_spk.sh should work fine as well the SPK on CPHUB is a frozen, tested and signed version while on git by bad chance you clone a WIP version. -I will check the install from build_spk on latest release anyway. 
I updated the readme to clarify the preferred use of signed SPK from CPHUB. 

2) The readme also refers to a Wiki please see here: https://wiki.z-hub.io/display/K4S . This could also help. In addition there is a GER Forum which is better suited for follow up questions than this issue log: https://www.synology-forum.de/forumdisplay.html?149-Zarafa . Your questions would be best placed here and you can also write in English; we / me will answer in English.

3)  For debugging and logging in a nutshell:
- if install fails Synology provides an error message to the user (sounds like not the case)
- for install issues check /var/packages/Kopano4s/target/log/package.log
- if start / run fails Kopano4s writes errors to the Docker Container (check container details->log)
   to try manually and capture errors run >/var/packages/Kopano4s/scripts/start-stop-status start.

4) For Zarafa migration (see also K4S-Wiki):
You have two options in general: a) via pst import. b) via database import.
A) you export from zarafa via outlook to pst files and then run >kopano-migration-pst to the files you copied to /volume1/kopano/backup/  which is the working directory in the k4s container
B) you import the zarafa database which requires you to run a specific kopano version, the so called migration edition which can be installed via k4s-beta-SPK or run via integrated script kopano4s-migration-zarafa.
Option b can make sense if you had zarafa or zarafa4home running on Synology, used zarafa-backup und injected this backup to kopano backup area and then all steps can be done in one go via >kopano4s-migration-zarafa. Option a involves more manual steps but is genericly simpler.

Hope that helps. -TosoBoso
PS: As this is not really a SW issue I would close this soon.

**Comment by cnoork** [comment]
Hi TosoBoso,

Thank you for directing to the Community Package Hub. For migration I was already aware of the choices but want first be in control to have it running.

With kind regards,
Chris
